from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from uuid import uuid4


class ProposalStatus:
    """Estados posibles para una propuesta de crédito"""
    INICIADO = "INICIADO"
    EN_PROGRESO = "EN_PROGRESO"
    COMPLETADO = "COMPLETADO"
    FALLIDO = "FALLIDO"


class CreditProposalCoril(BaseModel):
    """Modelo para la tabla credit_proposals_coril"""
    
    id: str = Field(default_factory=lambda: str(uuid4()))
    proposal_number: Optional[str] = None # Generated by DB trigger
    business_id: str
    deal_id: Optional[str] = None
    user_name: Optional[str] = None
    
    proposal_date: Any = Field(default_factory=datetime.utcnow) # Can be date or datetime
    total_amount: Optional[float] = None
    currency: str = "USD"
    status: str = ProposalStatus.INICIADO  # Nuevo campo de status
    
    pdf_s3_key: Optional[str] = None
    
    # JSONB content (puede ser None al inicio)
    proposal_data: Optional[Dict[str, Any]] = None
    
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        from_attributes = True
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }

class CreditProposalCorilCreate(BaseModel):
    """Modelo para crear un nuevo credit proposal coril"""
    business_id: str
    deal_id: Optional[str] = None
    user_name: Optional[str] = None
    proposal_date: Optional[Any] = None
    total_amount: Optional[float] = None
    currency: Optional[str] = "USD"
    status: Optional[str] = ProposalStatus.INICIADO
    pdf_s3_key: Optional[str] = None
    proposal_data: Optional[Dict[str, Any]] = None  # Ahora es opcional (se llena después)
