import os
#ANTHROPIC_API_KEY= os.environ['ANTHROPIC_API_KEY']
#MONGO_URI = os.environ['MONGO_URI']
BUCKET_NAME = os.environ['BUCKET_NAME']
# QUEUE_URL = os.environ['QUEUE_URL']
#DATABASE_URL = os.environ['DATABASE_URL']
DB_NAME = os.environ['DB_NAME']
# STATE_MACHINE_ARN = os.environ['STATE_MACHINE_ARN']
#WS_ENDPOINT = os.environ['WS_ENDPOINT']
MAX_RETRIES = 3
LAMBDA_FUNCTION_ARN = os.environ.get('TASK_CHECK_SLA_STATUS_LAMBDA_ARN')
EVENTBRIDGE_WORKFLOWS_BUS_NAME = os.environ['EVENTBRIDGE_WORKFLOWS_BUS_NAME']
# EVENTBRIDGE_WORKFLOWS_BUS_NAME_PROD = os.environ['EVENTBRIDGE_WORKFLOWS_BUS_NAME_PROD']